lr: 0.001
save_path: saved_models/disentangle_test.pt
tb_path: tensorboard/disentangle_test
data_path: 
  - test_tensor_JC_0.pt
  # - train_tensor_JC_0.pt
  # - train_tensor_JC_1.pt
  # - train_tensor_JC_2.pt
  # - train_tensor_JC_3.pt
  # - train_tensor_JC_4.pt
  # - train_tensor_JC_5.pt
  # - train_tensor_JC_6.pt
  # - train_tensor_JC_7.pt
  # - train_tensor_JC_8.pt
  # - train_tensor_JC_9.pt
  # - train_tensor_JC_10.pt
  # - train_tensor_JC_11.pt
  # - train_tensor_JC_12.pt
  # - train_tensor_JC_13.pt
  # - train_tensor_JC_14.pt
  # - train_tensor_JC_15.pt
  # - train_tensor_JC_16.pt
  # - train_tensor_JC_17.pt
  # - train_tensor_JC_18.pt
  # - train_tensor_JC_19.pt
  # - train_tensor_JC_20.pt
  # - train_tensor_JC_21.pt
  # - train_tensor_JC_22.pt
  # - train_tensor_JC_23.pt
validation_data_path:
  - test_tensor_JC_0.pt
test_data_path: 
  - test_tensor_JC_0.pt
batch_size: 5
v_frequency: 200
verbos: True
encoder_epochs: 1000
train_encoder: False
train_continue: False
epochs: 10000
instruments: [759] #, 417, 644, 97] #, 43, 701, 123, 37, 701, 488, 914, 224, 572, 82] #, 327]
num_workers: 0